# Generated by Django 2.0.5 on 2018-09-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='petpals_app/media'),
        ),
    ]
