# Generated by Django 2.0.5 on 2018-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0005_auto_20180922_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='petpals_app/profile_pics'),
        ),
    ]
