# Generated by Django 2.0.5 on 2018-09-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0007_auto_20180922_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, default='petpals_app/media/pawprint.png', null=True, upload_to='petpals_app/profile_pics'),
        ),
    ]
