# Generated by Django 2.0.5 on 2018-09-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0008_auto_20180922_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, default='petpals_app/profile_pics/pawprint.png', null=True, upload_to='petpals_app/profile_pics'),
        ),
    ]
