# Generated by Django 2.0.5 on 2018-09-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0009_auto_20180922_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
