# Generated by Django 2.0.5 on 2018-09-22 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0010_auto_20180922_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', message='Breeds can only allow uppercase letters, lowercase letters, and spaces')]),
        ),
    ]
