# Generated by Django 2.0.5 on 2018-09-22 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0011_auto_20180922_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
