# Generated by Django 2.0.5 on 2018-09-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpals_app', '0012_auto_20180922_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
